### ISSUE TITLE
Enhancement: Make keyword arguments of `clean_data`and `show_clean_params`compatible

### ISSUE THREAD

**Issue by vandalt** [SydneyAstrophotonicInstrumentationLab/AMICAL#77]
When using the cleaning functionality in a script, I find it convenient to use `**clean_params` with a pre-defined dictionary as done in the examples. This is especially useful in scripts that rely on a config file which contains an arbitrary (a priori unkown) set of of cleaning parameters. However, if I'm not mistaken, one set of cleaning params cannot currently contain _all_ cleaning parameters for both `clean_data`and `show_clean_data`, because of some kwargs that are in one but not the other

It would be convenient if the `clean_params` dictionary could contain all cleaning-related parameters without causing an error because of extra kwargs. I think a simple solution to this would be to add `**kwargs` in the signature of both functions. @DrSoulain , @neutrinoceros  do you think this would work ?

**Comment by neutrinoceros** [comment]
Adding **kwargs would work but it would be a bad kind of hack. Having *args and/or **kwargs in function signatures makes them harder to maintain and much less transparent to users. It would be extremely weird to see that a function has **kwargs in its signature if the arguments aren't used anywhere.
I haven't looked at the functions in question but depending on how many arguments they already share and how many are unique to either, we could adapt the signatures with much more accuracy.

**Comment by neutrinoceros** [comment]
So I studied this a little more and first we need to clarify which functions you're talking about:
- amical.data_processing.clean_data
- amical.data_processing.show_clean_params

here are their current signatures:
```python
def clean_data(
    data,
    isz=None,#
    r1=None,#
    dr=None,#
    edge=0,
    bad_map=None,#
    add_bad=None,#
    apod=True,
    offx=0,#
    offy=0,#
    sky=True,
    window=None,#
    darkfile=None,
    f_kernel=3,#
    verbose=False,
):
    ...

def show_clean_params(
    filename,
    isz,#
    r1,#
    dr,#
    bad_map=None,#
    add_bad=None,#
    edge=0,
    remove_bad=True,
    nframe=0,
    ihdu=0,
    f_kernel=3,#
    offx=0,#
    offy=0,#
    apod=False,
    window=None,#
):
    ...
```
where I've added a "#" sign on shared arguments.
Making them keyword only, even progressively (over the course of 2 or more releases), wouldn't work because 3 of them don't have default values in `show_clean_params` and are among the very first arguments, which means it should be considered valid to use them positionally, so we really can't move them to the end of the signature where we could make them keyword only.


## on the user side:
I think you should use a dedicate base dictionary with common arguments only, and possibly build specialised copies with the remaining of the arguments for each functions. It doesn't make sense from the library standpoint to support passing arbitrary arguments from one function to another.

## on the library side
A possible course of action is:
- formally deprecate `show_clean_params` in favour of an equivalent function but with a significantly different signature (where basically every argument would be keyword only)
- mark `clean_data` with a `@future_keyword_only` decorator for ... every arguments again (I wrote such a decorator here https://gist.github.com/neutrinoceros/3f703d63761794b5e966330d51436b3c)
- release

in a following release (likely AMICAL 2.0)
- drop the decorator and make arguments keyword only
- remove the deprecated function

So. I know how to do all of these but I don't have time for it these days, nor can I offer to seriously review for someone else at the moment. Feel free to implement it if you will.

An alternative would be to implement a global configuration system, where a single configuration object (probably a dict ?) could be passed to any function. I think this is not necessarily more elegant and I'm pretty sure it's much more work.

**Comment by vandalt** [comment]
Sorry, I was talking about `select_clean_data`, with the following signature:
```python
def select_clean_data(
    filename,
    isz=256,
    r1=100,
    dr=10,
    edge=0,
    clip=True,
    bad_map=None,
    add_bad=None,
    offx=0,
    offy=0,
    clip_fact=0.5,
    apod=True,
    sky=True,
    window=None,
    darkfile=None,
    f_kernel=3,
    verbose=False,
    ihdu=0,
    display=False,
):
...
```
But it does not change the fact that indeed, using `**kwargs` seems like a hack.

From the end-user perspective, I think it would still be interesting to specify a single dictionary for cleaning rather than sub-dictionaries for each function involved. For example, in the tutorial, we define `clean_param`, but it can only contain a subset of the cleaning parameters if used for both `show_clean_params` and `select_clean_data` (e.g. `sky=True` could not be in there, same for the `clip` kwargs, although they affect the "select" part more than cleaning).

In your proposed solution, wouldn't the two functions still have some non-shared kwargs that block us from passing a `**clean_params` dict that contains everything, even if the two become keyword-only ?

I'm not sure what the best way to enable this would be. Maybe a function (e.g. `select_clean_show`) that wraps both `select_clean_data` and `show_clean_params`, having all the arguments and passing them to the two functions ? Or maybe automatically calling `show_clean_params` when `display=True` in `select_clean_data` ?

For now, I'm just working around this in my script directly by splitting the user-provided dictionary properly, but I'd be happy to send a PR if you think this is worth adding.

**Comment by neutrinoceros** [comment]
> In your proposed solution, wouldn't the two functions still have some non-shared kwargs that block us from passing a **clean_params dict that contains everything, even if the two become keyword-only ?

Correct. What I'm proposing is essentially a way to mutate the signatures to get them closer to a state where they would be identical, but I have exactly 0 expertise or knowledge about the functionalities we're discussing so I'm coming to this with an engineering angle.
If it makes sense to have a higher level function that wraps these two and would be friendlier to use, it sounds like a great idea to me, and also much easier to implement, so consider you have my blessing to do just that.

**Comment by vandalt** [comment]
Great! I can send a PR for this. I feel that including a call to `show_clean_params` in `select_clean_data` when `display=True` would be a good option, given that `show_clean_params` just displays stuff. The extra keyword arguments could be added at the end of `select_clean_data` and there would be no need to add an extra function that basically does the same thing as `select_clean_data`, but with some extra plotting. Do you both (@DrSoulain and @neutrinoceros) agree with this approach ?

**Comment by neutrinoceros** [comment]
> I feel that including a call to show_clean_params in select_clean_data when display=True would be a good option, given that show_clean_params just displays stuff.

sounds good to me.
